project_id = "oruslrvpmdhtnrsgoght"

[functions.generate-image]
verify_jwt = false

[functions.image-worker]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.ticto-webhook]
verify_jwt = false

[functions.trial-daily-credits]
verify_jwt = false
