project_id = "oruslrvpmdhtnrsgoght"

[functions.generate-image]
verify_jwt = false

[functions.image-worker]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.ticto-webhook]
verify_jwt = false

[functions.trial-daily-credits]
verify_jwt = false

[functions.claim-reward]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-asaas-checkout]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.process-asaas-payment]
verify_jwt = false

